sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t daniel/noderedis-dev .

script:
  - docker run daniel/noderedis-dev npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multicontainer-app"
  env: "Multicontainerapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-814971353988"
  bucket_path: "multicontainer-app"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: main
